### ISSUE TITLE
How to use abl-tools to generate a timeVaryingMappedBC?

### ISSUE THREAD

**Issue by fastlabb** [NWTC/abl#1]
I had used the Mann box method to generate a turbulent field by Mann 64bit turbulence generator ( which is downloaded from http://www.hawc2.dk/download/pre-processing-tools ).

How do I generate a timeVaryingMappedBC for OpenFOAM? I see that _stochastic_turbulence.py_ seems to be able to complete this task, but I don't know how to use it. Can you give me an example?

I really appreciate any help you can provide.

**Comment by ewquon** [comment]
Thank you for reaching out. I apologize that these scripts are very much a work in progress and if you have suggestions for improvement or development they would be very much appreciated.

If you need to convert inflow data to timeVaryingMappedBC, here is some example code that should get you started: https://github.com/NWTC/datatools/blob/master/SOWFA/constant/boundaryData_generation_example.py
Instead of calling `bd.CartesianPatch.write_profiles()`, you could directly call `bd.write_data()` with your Mann inflow field. If you look at the docstring for `write_data`, it will describe the expected data shape.

Let me know if that works for you!
